S3_CREDS = {
	"AWS_S3_ACCESS_KEY_ID" : '',
	"AWS_S3_SECRET_ACCESS_KEY" : '',
	"AWS_STORAGE_BUCKET_NAME" : '',
	"AWS_DOMAIN" : "",
	"AWS_BUCKET_NAME": "",
	"AWS_ACCESS_KEY": "",
	"AWS_SECRET_ACCESS_KEY": ""

}



