S3_CREDS = {
	"AWS_S3_ACCESS_KEY_ID" : 'AKIA4PSFYKYPLQHTFQUL',
	"AWS_S3_SECRET_ACCESS_KEY" : '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',
	"AWS_STORAGE_BUCKET_NAME" : 'sso-ms',
	"AWS_DOMAIN" : "http://sso-ms.s3.amazonaws.com/",
	"AWS_BUCKET_NAME": "sso-ms",
	"AWS_ACCESS_KEY": "AKIA4PSFYKYPLQHTFQUL",
	"AWS_SECRET_ACCESS_KEY": "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"

}

AWS_S3_ACCESS_KEY_ID = 'AKIA4PSFYKYPLQHTFQUL'
AWS_S3_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'sso-ms'

